"""new_field

Revision ID: 8b223246724e
Revises: a1e9b0f4b6c6
Create Date: 2025-01-21 16:28:21.855552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b223246724e'
down_revision: Union[str, None] = 'a1e9b0f4b6c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('square_calculation_task', sa.Column('celery_task_id', sa.String(), nullable=True))
    op.add_column('square_calculation_task', sa.Column('square_info_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'square_calculation_task', 'square_info', ['square_info_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'square_calculation_task', type_='foreignkey')
    op.drop_column('square_calculation_task', 'square_info_id')
    op.drop_column('square_calculation_task', 'celery_task_id')
    # ### end Alembic commands ###
