"""add_log_table

Revision ID: 9fc3f71ba2a8
Revises: dd029c5a0974
Create Date: 2025-02-26 12:08:53.552957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc3f71ba2a8'
down_revision: Union[str, None] = 'dd029c5a0974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
