"""create_default_admin

Revision ID: 4e0c3cb83624
Revises: dd029c5a0974
Create Date: 2025-01-24 13:56:50.238373

"""
import asyncio
from typing import Sequence, Union

from config import settings
from config.db_config import get_session
from database import User
from infrastructure.enums.user_type import UserType
from infrastructure.utils.user_utils import hash_password, convert_name_to_username

# revision identifiers, used by Alembic.
revision: str = '4e0c3cb83624'
down_revision: Union[str, None] = 'dd029c5a0974'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


async def upgrade_async():
    async for db_session in get_session():
        full_name = settings.DEFAULT_ADMIN_FULL_NAME
        username = convert_name_to_username(full_name)
        password = hash_password(settings.DEFAULT_ADMIN_PASSWORD)
        user = User(
            full_name=full_name,
            username=username,
            user_type=UserType.ADMIN.value,
            password=password,
        )
        db_session.add(user)
        await db_session.flush()
        await db_session.commit()


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    asyncio.run(upgrade_async())

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
