"""add_models

Revision ID: 249d27eb3fe7
Revises: b8f16893ee0e
Create Date: 2025-01-17 12:24:24.706325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '249d27eb3fe7'
down_revision: Union[str, None] = 'b8f16893ee0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('square_calculation_task',
    sa.Column('input_value', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('square_info',
    sa.Column('original_value', sa.Integer(), nullable=True),
    sa.Column('square_count', sa.Integer(), nullable=True),
    sa.Column('squares', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_of_calculation', sa.Numeric(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('modified_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('square_info')
    op.drop_table('square_calculation_task')
    # ### end Alembic commands ###
